admin:
  existingSecret: ""
  user: admin
  password: admin123

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 10Gi
  storageClassName: standard

grafana.ini:
  server:
    root_url: "http://192.168.1.8:3000/"
