admin:
  existingSecret: grafana-admin-secret  # Reference to a secret for admin credentials

persistence:
  enabled: true
  size: 5Gi
  storageClassName: "local-path"  # Change as needed

service:
  type: LoadBalancer  # Change to ClusterIP if you don't need external access

ingress:
  enabled: false
  hosts:
    - host: grafana.example.com  # Replace with your actual domain
      paths:
        - /


# Add additional configurations as needed
