# grafana-values.yaml

admin:
  existingSecret: grafana-admin-secret  # Reference to a secret for admin credentials

image:
  repository: grafana/grafana  # Default Grafana image
  tag: "latest"  # Specify the desired image tag, e.g., "9.4.3" or "latest"

persistence:
  enabled: true
  size: 5Gi
  storageClassName: "local-path"  # Change as needed

service:
  type: LoadBalancer  # Change to ClusterIP if you don't need external access

ingress:
  enabled: false
  hosts:
    - host: grafana.example.com  # Replace with your actual domain
      paths:
        - /
